mindmap
  root((Markusevangeliet\n67–75 e.Kr\nPilotöversättning 2021))
    ANONYM FÖRFATTARE
      Papias, vars synpunkter vi inte känner från hans egna skrifter utan via Eusebios av Caesarea, säger omkring år 130 om Markus att han var Petrus tolk, samt att Markus inte skrev ned berättelserna i rätt ordning, eftersom han aldrig träffat Jesus. Wikipedia
    MAGI
      Ta detta, det är min kropp. Och han tog en bägare, tackade Gud och gav åt dem, och de drack alla ur den. Han sa: Detta är mitt blod, förbundsblodet som blir utgjutet för många.
      Han tog den blindes hand och ledde honom ut ur byn. Sedan spottade han på hans ögon, lade sina händer på honom och frågade: Ser du något? Han såg upp och sa: Jag ser människorna, men de ser ut som träd som går omkring. Då lade han än en gång händerna på hans ögon, synen fick skärpa.
    JESU LÄRA\nENLIGT MARKUS
      LIDANDET
        Den som vill följa i mina spår måste förneka sig själv och ta sitt kors och följa mig.
        För varje människa ska saltas med eld. Salt är bra, men om det mister sin sälta, hur ska ni då ge det kraft igen? Ha salt i er själva och håll fred med varandra.
      SKILSMÄSSA
      TREENIGHETEN
        Israel, Herren är vår Gud. Herren är en.
      SYNDERNAS FÖRLÅTELSE
        För inte heller Människosonen har kommit för att bli tjänad utan för att tjäna och ge sitt liv till lösen för många.
        Allt ska människorna få förlåtelse för, både synder och hädelser, hur mycket de än hädar. Men den som hädar den heliga anden får aldrig någonsin förlåtelse utan är skyldig till evig synd.
      Det som kommer ut ur människan, det gör henne oren. För inifrån, ur människors hjärtan, kommer de onda tankarna
        DRÅP/MORD
        SEX
        STÖLD
        LÖGN
        RÄTT TANKE OCH TAL
        TRO OCH HOPP
          Allt är möjligt för den som tror.
          Sannerligen säger jag er: Om någon säger till det här berget Låt dig lyftas upp och bli kastad i havet, och inte tvivlar i sitt hjärta, utan tror att det ska hända, då kommer det att bli så. Därför säger jag er: Allt som ni ber om i er bön, tro att ni har fått det och ni ska få det. Om ni står och ber, och ni har något emot någon, förlåt då den människan, så ska också er far i himlen förlåta er era felsteg.
        DÖMMA ELLER INTE
          Ge akt på det ni hör. Med samma mått som ni mäter med ska det mätas upp åter, och det med råge. För åt dem som har ska ges, men från dem som inte har ska tas också det de har.
        ÄLSKA GUD
        ÄLSKA DIN NÄSTA
      RIKEDOM\nPENGAR
        En sak fattas dig. Gå och sälj allt du har och ge åt de fattiga. Då ska du få en skatt i himlen. Kom sedan och följ mig.
        Det är lättare för en kamel att komma igenom ett nålsöga än för en rik att komma in i Guds rike.
      UPPSTÅNDELSEN
        För när de har uppstått från de döda, varken gifter de sig eller blir bortgifta utan är som änglar i himlen.
      FALSKA MESSIAS
        För falska messias och falska profeter ska träda fram och göra tecken och under för att försöka föra de utvalda vilse.
        När den dagen eller timmen kommer vet ingen, varken änglarna i himlen eller Sonen, ingen utom Fadern.