name: Lint PowerShell and Python

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Super Linter
        uses: super-linter/super-linter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main

          # Only validate these languages
          VALIDATE_POWERSHELL: true
          VALIDATE_PYTHON: true

          # Only look at these file types (ignore everything else)
          FILTER_REGEX_INCLUDE: '(\.ps1|\.psm1|\.psd1|\.pssc|\.py)$'

          # Respect your .gitignore and lint the whole codebase on main
          IGNORE_GITIGNORED_FILES: true
          VALIDATE_ALL_CODEBASE: true
